id: I09377079
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:54:36+00:00'
last_modified: '2022-06-07T18:50:32.634754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28792
  title: ཆོས་འབྱུང་མཁས་པའི་དགའ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFBF:
      image_group_id: I4640
      title: ''
      total_pages: 876
      order: 1
      base_file: FFBF.txt
    33EE:
      image_group_id: I4641
      title: ''
      total_pages: 712
      order: 2
      base_file: 33EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
