id: I09377079
legacy_id: P003283
ocr_import_info:
  bdrc_scan_id: W28792
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T18:49:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:38:42.400568+00:00'
last_modified: 2022-09-02 16:41:50.946676
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28792
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28792
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་འབྱུང་མཁས་པའི་དགའ་སྟོན།
  author: དཔའ་བོ ༠༢་གཙུག་ལག་འཕྲེང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.7508071686725926
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I4641:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4641
      total_pages: 712
      volume_number: 2
      volume_pages_bdrc_intro: 0
    order: 2
    base_file: I4641.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.74519581815504
    legacy_id: v002
  I4640:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4640
      total_pages: 876
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4640.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7539533827356633
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
