id: P003283
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:33.490717
source_metadata:
  id: bdr:W28792
  title: ཆོས་འབྱུང་མཁས་པའི་དགའ་སྟོན།
  author: ''
  volumes:
    df700e7b181542a4a8fc24116caf02f3:
      image_group_id: I4640
      title: ''
      volume_number: 1
      total_pages: 876
      base_file: v001.txt
    0041e53917b84e06aa0cdf0f1ba4ac80:
      image_group_id: I4641
      title: ''
      volume_number: 2
      total_pages: 712
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
